[build]
builder = "dockerfile"

[deploy]
startCommand = "./start-test.sh"
healthcheckPath = "/docs"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PORT = "8000"
